### ISSUE TITLE
Restrict scope to .blade.php files only.

### ISSUE THREAD

**Issue by IanCaunce** [austenc/blade-spacer#9]
Mustache has a similar syntax. When there is no scope, spaces are added for both blade and mustache which means I have to manually remove them. Restricting the file scope would fix this issue.

**Comment by austenc** [comment]
The file scope is currently 'restricted' to HTML and Blade files. Initially I had it restricted to only blade files, but that means users will need to have the Laravel Blade Highlighter plugin installed for it to work, hence why I enabled it for text/html files. I'd love to make it compatible with mustache as well.. perhaps I can restrict it to php files instead of html.. would that work for you or would the problem still exist?

**Comment by austenc** [comment]
You may also look into overriding the keymap for your use-case. I believe you can do this just like user preference files.

[Here's the keymap for windows](https://github.com/austenc/blade-spacer/blob/master/Default%20(Windows).sublime-keymap). I believe you can copy that into your key bindings and update the scoping for now.

**Comment by IanCaunce** [comment]
Thanks for your reply. I currently have a plugin installed which highlights mustache files as HTML. I bet that is why the extra space is added.  I think restricting the scope to php files only would solve the issue but I am unsure if this would have any negative side effects for other users.

**Comment by IanCaunce** [comment]
Sorry pressed the wrong button to post a comment

**Comment by austenc** [comment]
@IanCaunce I'll try to check it out tonight on a fresh copy of sublime and see what it does in terms of trying to associate blade files in a vanilla install. We should be able to switch the association to php instead of html without causing too much trouble. Thanks for bringing this up.
